export default {
  login: "sahil20021",
  id: 84684047,
  node_id: "MDQ6VXNlcjg0Njg0MDQ3",
  avatar_url: "https://avatars.githubusercontent.com/u/84684047?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/sahil20021",
  html_url: "https://github.com/sahil20021",
  followers_url: "https://api.github.com/users/sahil20021/followers",
  following_url:
    "https://api.github.com/users/sahil20021/following{/other_user}",
  gists_url: "https://api.github.com/users/sahil20021/gists{/gist_id}",
  starred_url: "https://api.github.com/users/sahil20021/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/sahil20021/subscriptions",
  organizations_url: "https://api.github.com/users/sahil20021/orgs",
  repos_url: "https://api.github.com/users/sahil20021/repos",
  events_url: "https://api.github.com/users/sahil20021/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/sahil20021/received_events",
  type: "User",
  site_admin: false,
  name: null,
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 2,
  public_gists: 0,
  followers: 1,
  following: 0,
  created_at: "2021-05-23T19:59:00Z",
  updated_at: "2023-10-01T06:53:17Z",
};
